services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hostelDB

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - backend
    environment:
      - PORT=4000
      - ALERTS_SERVICE_URL=http://backend:5000
      - ANALYTICS_SERVICE_URL=http://backend:5000
      - ROOMS_SERVICE_URL=http://backend:5000
      - DEVICES_SERVICE_URL=http://backend:5000
      - JWT_SECRET=supersecretkey 

  rooms:
    build: ./services/rooms
    container_name: rooms
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hostelDB

  devices:
    build: ./services/devices
    container_name: devices
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hostelDB

  alerts:
    build: ./services/alerts
    container_name: alerts
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hostelDB

  analytics:
    build: ./services/analytics
    container_name: analytics
    ports:
      - "5004:5004"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hostelDB

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"

  auth:
    build: ./services/auth
    container_name: auth
    ports:
      - "5005:5005"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/hostelDB
      - JWT_SECRET=supersecretkey    

volumes:
  mongo_data: